
development:
  adapter: postgresql
  encoding: unicode
  database: piotr
  pool: 5

test:
  adapter: postgresql
  encoding: UTF8
  database: piotr
  pool: 5

production:
  adapter: postgresql
  encoding: UTF8
  database: piotr
  pool: 5
  username: piotr